name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  rax3000m-op23_05_4:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          sudo apt install -y u-boot-tools device-tree-compiler
      - name: Test
        run: |
          wget https://downloads.openwrt.org/releases/23.05.6/targets/mediatek/filogic/openwrt-23.05.6-mediatek-filogic-jcg_q30-pro-squashfs-sysupgrade.itb && \
          python3 patch_itb.py openwrt-23.05.6-mediatek-filogic-jcg_q30-pro-squashfs-sysupgrade.itb patched.itb && \
          (echo "90840502210d1cd311967f9b8024b7fb  patched.itb" | md5sum -c)
  rax3000m-op24_10_0_rc2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          sudo apt install -y u-boot-tools device-tree-compiler
      - name: Test
        run: |
          wget https://downloads.openwrt.org/releases/24.10.4/targets/mediatek/filogic/openwrt-24.10.4-mediatek-filogic-jcg_q30-pro-squashfs-sysupgrade.itb && \
          python3 patch_itb.py openwrt-24.10.4-mediatek-filogic-jcg_q30-pro-squashfs-sysupgrade.itb patched.itb && \
          (echo "306f1c5407de85645fbae31757ff3564  patched.itb" | md5sum -c)
